
class Lankswing
    def self.frame_one
        puts "
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhsssshmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhsooooooosmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNyo+:::::::+omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMmhohyo/:-----//::shsshMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNh/:s+//---/+//+-o:/odMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNh/oso/oo/::/ss/ymNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+ss+sy-.:ss+y+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNNydy/+..../+:NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMN/:-+yds////oso/hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMhhhhhyyoosyyyy--NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyso::oshy+.oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmNdddysssso+-:/ohmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmNmmNNNNds//-/-//yMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmmNd+:.-`-smMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo-.``-yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy:.  /dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh/.  /dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh/.  +dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy- `dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNh+.`:mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhs/.`.+ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms-dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdMMMMMMMMMMM
"
    sleep(0.09)
    system 'clear'
    end



    def self.frame_two
        puts "
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNdsssyhmMMMMMMMMMMMMMmyyysshMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhysoooooosyMMMMMMMMMdho:```./hMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNhysoo++++++osdNddmd+:.```./+hNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMmysmhyo/:------:/sho//.```-/ohNNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMms-ohs+---:----:oody+::-osdNNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMmy+s+/::/+:-/+os:NdyssyMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMhmo/++yooosso:omosMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNdNooy/y.//-:+.dydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMN/::hNms++////ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMhhhNmh+-ooo++omdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdyyssssssyhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmMhhdhyssssyhsmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmNmdmNmddddddhNd+sMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmmmdmmms+::sMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs//-``--oMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs::.  /-+MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs:/.  /-+MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs-:.  /-+MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs...``--oMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+.``--.+hMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd:-....-:smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdd+---./hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyhNhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"
sleep(0.09)
system 'clear'
end

    def self.frame_three
        puts "
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+:omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMymNMMMNmy:``-oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMs/shy:+Nh+. `yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNs-.-/mMMms. `omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMy//++-sMMMN+.``:dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMdhhmMNhhdNNNh/.``ohhmMMMMMMMMMMMmyyysshMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNMMMMMMNdhysoo++oso/yNMMMMMMMdho:```./hMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNysoooooo+/::-:omddmd+:.```./+hNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMmhydssoooo:-------/++/.```-/ohNNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMmdmNdysssso------/--:/::-osdNNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMmNyyys+:/+/-:+s:ooossyMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMh///os:+++o+::-y+sMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNmy/:od-No://`:+NNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMN/:hsyNhoNmhoosmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMhhhNMmyhsooooo++NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmyssshysssssNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmNdhdysssssyhdmNmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmNmdmNmddddddhhmosMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmmmdddmso:/sMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs//-``--oMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs::.  /-+MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs:/.  /-+MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs-:.  /-+MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs...``--oMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+.``--.+hMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd:-....-:smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdd+---./hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyhNhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"
sleep(0.09)
system 'clear'
end

    def self.frame_four
        puts "
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNNMMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNhhNhyhh+NhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMmosoo+////ooooshhhhhhs:dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMdsoo/:.````-::/+-````--`./::ommMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMdhy+/.`     ..`.:-:....`  `-..-/ysssshMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMs+o/:       ```-/+/.----.`-.` `..-../syMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMyss/:``      `-/+++:////-.`````-.`````./mMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMmyo+:-`````.:+sy+ooooso/o-````..````..-+sshMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMmoso+/::::ooyyo//oooooosh+-`  ``....:.``.+MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMdoodyoss+o//:---:::/+oosdds-.``````:-.``:mMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNNMmmmyo/-:----/::--:oyydh/.```  `.:..``.NMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMmhss++:--:+o++/:-:s/:+o:-o:`   ::.` `:MMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNdho++++/:////o/+//oysyMmo`  ::.`` `/NMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMhy+::--syo:/y-mdosMMMMMm/``::..`  `dNMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNmmy/:--.///sdomydNMMMMMMs``-:..`   -hMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMN/N/:+yyysoodds//hNMMMMMMMh/``-.``   `yMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMhMhyo://Nhsyyy::.+hNNNMMMMd. ..`    `yMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdyooyssssyNmsss+//ossys. ```    `yMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmMmddssyyydmmNmmy+:`````.-. ``     `yMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmNmdmNNNNNmdhhNdsosyy/:--.`       `:hMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmmmdmmms+:/sMMMMMd: ``     `.mMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs//-``--oMMMMmo`.:.`    `/NMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs::.  /-+MMMM++dmM:.`  `/MMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs:/.  /-+MMMMMMMMM:.` `-MMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs-:.  /-+MMMMMMMMM:.``/mMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs...``--oMMMMMMMMN:`-omMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+...--.+hMMMMMMMd:-+NMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd:-....`-smMMMMMMMmyoNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdd+--.`-:NMMMMMMMMNmMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyhd:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMM
"
sleep(0.09)
system 'clear'
end
    def self.frame_five
        puts "
MMMMMMMMMMMMMMNNMMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNhhNhyhh+NhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMmosoo+////ooooshhhhhhs:dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMdsoo/:.````-::/+-````--`./::ommMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMdhy+/.`     ..`.:-:....`  `-..-/ysssshMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMs+o/:       ```-/+/.----.`-.` `..-../syMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMyss/:``      `-/+++::///-.`````-.`````./mMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMmyo+:-`````.::/+o+//+ss::.````..````..-+sshMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMmoso+/::::o::/+:/oooooosoo/:: ``...-/:-`.+MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMdoodyoss+y+o/:oooooooooossss+.`````//-``/mMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNNMmmmyo/dhyssoooooooooshdyssy:` `.:-.---NMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMmhss/yyyhssooooooooshdyyyhmo   :/-...+MMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNdd++osysysssssssssydNNNMy`  ::.-- `/NMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMh+:-/ysyyhdyssssssymMMMm/``::..` `/mMMMMMMMMMMM
MMMMMMMMNMMMMMMMMMMMMMMMMMMNmhhyooyoyhddhhyyyysyhMMMs``-:..``-:ohmNMMMMMMMM
MMMMMMMM+dMMMMMMMMMMMMMMMMN/Nshs/ymdho++/smhmmdhdMMMh/``-..-+:``-/sdMMMMMMM
MMMMMMMM-/mMMMMMMMNNNmhyshNho+:-/yhyhyyyodN:+hNNNMMMMd. ...../--/yNMMMMMMMM
MMMMMMMM-.odNhyoo+/:--..:+yMysyhdysyyyyyssNyss+//ossys. ```  .:/hMMMMMMMMMM
MMMMMMMM.`-:/..```````://+sMmMdyhyyyyyyyhmmmy+:`````.-. ``   `.:yNMMMMMMMMM
MMMMMMMM/.`.-.`.```:yhNMmdmMmNmddmmMNNNNmmmdsosyy/:--.`   ```/:+ydNMMMMMMMM
MMMMMMMMM/ ```.-`` :NMMMMMMMMNyyddddmddddo+:/sMMMMMd: ``  :+:/`.-/sdMMMMMMM
MMMMMMMMMs.   ``   ./MMMMMMMMM+.-:ohNs//-``--oMMMMmo`.:.` -//.``-+syMMMMMMM
MMMMMMMMMMo.       ``/dNMMMMMo.``:NMMs::.  /-+MMMM++dmM:.` `-/+:+hNNMMMMMMM
MMMMMMMMMMMy.     `````/dNNMM.` `+MMMs:/.  /-+MMMMMMMMM:...-+/shNMMMMMMMMMM
MMMMMMMMMMMNh``    `.`.`-::yh.``.yMMMs-:.` /-+MMMMMMMMM:--:omyNMMMMMMMMMMMM
MMMMMMMMMMMMNd-`   ``..--.`````./mmmmo....`..oMMMNNNy++...-oNNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMs:``  ``..-:-`  ````````....-+yNyy:--.``.sy/:ydMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNh/`   ``..--..``````.-------::-..--`-+NMMddMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNs-.``````.-:--.````...````````.:/sdMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMh/..` ```......-..:--``.--//-.:+shNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNNm+++-``````.-:+oysohNys+-.:ohMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhhh+oo/`:osdNMMMmhoyNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy+-`` .+ohMMMMMNNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmys/.+NddMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyyymMMMMMMMMMMMMMMMMMMMMM
"
sleep(0.09)
system 'clear'
end

    def self.frame_six
        puts "
MMMMMMMMMMMMMMMMMNNMMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNhhNhyhh+NhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMmosoo+////o+o++ddddddhosyNmyoMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMdsoo/:.``.-+-://..`/://`:os/--mmMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMdhy+/.```.:+:``.:/- /+:. `./+/`..ossshMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMs++:: ````..//:::.``.-::/.+.--``` ``:syMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMo:-.:...-----///:/:---/++/-``...-.``..`+mMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNs--:---:-..`.-++oyhooooyyo.` `.....`.----ssshMMMMMMMMMMMMMMM
MMMMMMMMMMMNdh--:::-:.`` ./sohdhsooooooosho.``` ``...-/:/--oMMMMMMMMMMMMMMM
MMMMMMMMNMho:--//:-..` `/sysyNyo+:::::::+om+++:..`````//---/mMMMMMMMMMMMMMM
MMMMMMMMsy+:-`.//:-```.+yss/yyo:--:---:/--:ysosss:.```.:-:-.:NMMMMMMMMMMMMM
MMMMMMMMho:-. :/o/-``+yysyh/:s+/::---/+++-::/odyyys/.` :/:-``/MMMMMMMMMMMMM
MMMMMMMMMo-/+:+dmy/./Mhhmdhdh/oso/oo+/:/ss/yyydNNNMy...:::-` `+NMMMMMMMMMMM
MMMMMMNyN/-::+hMMMd+MMNNMmssN+ss+sy/-:ss+y+mhsymMMMm/``:::-`  `dMMMMMMMMMMM
MMMMMNd:o/.-/NMMMMMNMMMMMNdsmhmy:+..../+:NmhyysyhMMMs.``-:-`   :ymNMMMMMMMM
MMMNdo:``-/+yMMMMMMMMMMMMMMdMh+oyo////osy//ymmdhdMMMh/  .-.`   `-/sdMMMMMMM
MMMNdyo--/hNMMMMMMNNNmhyshNMM-.omssoossyyh/./yNyyyNMMd  ````    /yNMMMMMMMM
MMMMMMNd+:odNhyoo+/:--..:+yMMyshdsy::+ssyMmssys/::oyho   ``     sMMMMMMMMMM
MMMMMMMM-`-:/..```````://+sMmNNmmyysssyhmNmmds/:.``.--         `sNMMMMMMMMM
MMMMMMMM:``.-.`.```:yhNMmdmMmNdhdNMNNNNmhhNdysydh/:.``  `     `-odNMMMMMMMM
MMMMMMNN+.````.-`` :NMMMMMMMMNhhmmddmdmmms+:/sMMMMNo`  ```   `..-/sdMMMMMMM
MMMMMNhs-:/-  ``   ./MMMMMMMMM+.-:ohNs//-``--oMMMd/.`.:.`   `..`-+syMMMMMMM
MMMMMMMMsd+`       ``/dNMMMMMo.``:NMMs::.  /-+MNo:-+dmM-`  `./+:+hNNMMMMMMM
MMMMMMMMMm+:-.`   `````/dNNMM.` `+MMMs:/.  /-+MMMMMMMMM````-+/shNMMMMMMMMMM
MMMMMMMMhdo-...``  `.`.`-::yh.``.yMMMs-:.` /-+MMMMMMMNy...-omyNMMMMMMMMMMMM
MMMMMMMM:/-` ``..` ``..--.`````./mmmmo....`..oMMMNNNy/-...-oNNMMMMMMMMMMMMM
MMMMMMMMy/-.``.s/.`  ``..-:-`  ````````....-+yNys:--.``.sy/:ydMMMMMMMMMMMMM
MMMMMMMMMMh+-.oMNh/``  ``..--..``````.-------:/-`...`-+NMMddMMMMMMMMMMMMMMM
MMMMMMMMMMmdddMMMNh.-```````.-:--.````...``...-``.-:sdMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNy/.``.....` ```......--.:--`.--.-+-.:+shNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMso/.``-odNNm+++.````...://-.` `.:o+-.:ohMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNh/.dMMMMMMMM++y-o.``.-.--.`-omMmhoyNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNhMMMMMMMso--+-.`` ``.--+:oMMMMMNNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+oMmoo-`.-/-+NddMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMo++oyyymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"
sleep(0.09)
system 'clear'
end

    def self.animation
    5.times do
        Lankswing.frame_one
        Lankswing.frame_two
        Lankswing.frame_three
        Lankswing.frame_four
        Lankswing.frame_five
    end
    end

    def self.go
    system 'clear'
    self.animation
    puts "\n\n Whirlybird\n\n"
    end
end